set ipName clk_wiz_dac
create_ip -name clk_wiz -vendor xilinx.com -library ip -version 6.0 -module_name ${ipName}
set_property -dict [list \
  CONFIG.CLKOUT1_REQUESTED_OUT_FREQ {100} \
  CONFIG.PRIM_IN_FREQ {125} \
  CONFIG.RESET_PORT {reset} \
  CONFIG.RESET_TYPE {ACTIVE_HIGH} \
  CONFIG.CLKOUT1_DRIVES {BUFGCE} \
  CONFIG.CLKOUT2_DRIVES {BUFGCE} \
  CONFIG.CLKOUT3_DRIVES {BUFGCE} \
  CONFIG.CLKOUT4_DRIVES {BUFGCE} \
  CONFIG.CLKOUT5_DRIVES {BUFGCE} \
  CONFIG.CLKOUT6_DRIVES {BUFGCE} \
  CONFIG.CLKOUT7_DRIVES {BUFGCE} \
  CONFIG.ENABLE_CLOCK_MONITOR {false} \
  CONFIG.FEEDBACK_SOURCE {FDBK_AUTO} \
  CONFIG.USE_SAFE_CLOCK_STARTUP {true} \
  CONFIG.PRIM_SOURCE {Global_buffer} \
  CONFIG.CLKOUT1_JITTER {124.615} \
  CONFIG.CLKOUT1_PHASE_ERROR {96.948} \
  CONFIG.MMCM_BANDWIDTH {OPTIMIZED} \
  CONFIG.MMCM_CLKFBOUT_MULT_F {8.000} \
  CONFIG.MMCM_CLKIN2_PERIOD {10.000} \
  CONFIG.MMCM_CLKOUT0_DIVIDE_F {10.000} \
  CONFIG.MMCM_COMPENSATION {ZHOLD} \
  CONFIG.MMCM_DIVCLK_DIVIDE {1} \
  CONFIG.PRIMITIVE {MMCM} \
] [get_ips ${ipName}]
generate_target {instantiation_template} [get_files $::env(OUT_DIR)/$::env(VIVADO_PROJECT).srcs/[get_filesets sources_1]/ip/${ipName}/${ipName}.xci]